image: gossin/iikos-ci:latest
pipelines:
  default:
    - step:
        script:
          - find . -type f -name '*.c' | xargs --no-run-if-empty -n1 gcc -pthread -Wall -Werror
          - clang-tidy -checks='*' -warnings-as-errors='*' *.c --
